-- Adds voting + hot ranking support for posts. Safe to run multiple times.

CREATE TABLE IF NOT EXISTS "Vote" (
  "userId" TEXT NOT NULL,
  "postId" TEXT NOT NULL,
  "value" INTEGER NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "Vote_pkey" PRIMARY KEY ("userId", "postId"),
  CONSTRAINT "Vote_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "Vote_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "Vote_postId_idx" ON "Vote" ("postId");

ALTER TABLE "Post"
  ADD COLUMN IF NOT EXISTS "upvotes" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "downvotes" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "score" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "commentCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "hotScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lastActivityAt" TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS "Post_lastActivity_idx" ON "Post" ("lastActivityAt");
